<Project>
  <PropertyGroup>
    <VersionPrefix>3.0.0</VersionPrefix>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <FileVersion>3.0.0.0</FileVersion>
    <InformationalVersion>3.0.0-dev.2</InformationalVersion>
    <Company>DualLink</Company>
    <Product>DualLink Application Booster</Product>
    <Copyright>Copyright © 2026 DualLink</Copyright>
  </PropertyGroup>
</Project>
