<Project>
  <PropertyGroup>
    <VersionPrefix>4.1.0</VersionPrefix>
    <AssemblyVersion>4.1.0.0</AssemblyVersion>
    <FileVersion>4.1.0.0</FileVersion>
    <InformationalVersion>4.1.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Company>DualLink</Company>
    <Product>DualLink Application Booster</Product>
    <Copyright>Copyright © 2026 DualLink</Copyright>
  </PropertyGroup>
</Project>
